# -*- coding: utf-8 -*-
"""EDA_proyecto_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WU0L9SqgyKzkCMHAjsdsOpgmFZl0fJm_

## 📊 Exploración de Datos (EDA)
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json

# Cargar el dataset, especificando el delimitador como punto y coma
file_path = '/content/samples_202605092028.csv'
df = pd.read_csv(file_path, sep=';')

print(f"Dataset cargado exitosamente desde: {file_path}")
print("Primeras 5 filas del dataset:")
display(df.head())

"""### 🔍 Información General del Dataset"""

# Mostrar información general del DataFrame (tipos de datos, valores no nulos)
print(df.info())

# Mostrar estadísticas descriptivas para columnas numéricas
print("\nEstadísticas descriptivas:")
display(df.describe())

"""### ⏳ Extracción de Características JSON y de Tiempo"""

# Convertir 'captured_at' a datetime y extraer características
df['captured_at_dt'] = pd.to_datetime(df['captured_at'], utc=True)
df['hour_of_day'] = df['captured_at_dt'].dt.hour
df['day_of_week'] = df['captured_at_dt'].dt.dayofweek
df['month'] = df['captured_at_dt'].dt.month

# Función para parsear la columna 'features' (JSON-like string)
def parse_features(features_str):
    try:
        # Limpiar la cadena para que sea un JSON válido
        cleaned_str = features_str.replace('""', '"')
        # Convertir la cadena a un diccionario
        return json.loads(cleaned_str)
    except json.JSONDecodeError:
        return {}

# Aplicar la función y expandir el diccionario en nuevas columnas
features_expanded = df['features'].apply(parse_features).apply(pd.Series)

# Columnas a eliminar del DataFrame original antes de concatenar las expandidas
# Eliminamos 'features' y 'captured_at' originales. Mantenemos 'label' y 'phase' para codificación posterior.
# Eliminamos las columnas numéricas que serán reemplazadas por las de 'features_expanded' para evitar duplicados.
columns_to_drop_from_original = ['features', 'captured_at', 'knee_angle_mean', 'trunk_inclination']
df = df.drop(columns=columns_to_drop_from_original, errors='ignore')

# Unir las nuevas columnas (las de tiempo y las expandidas de features) al DataFrame original
df = pd.concat([df, features_expanded], axis=1)

# Eliminar la columna temporal 'captured_at_dt' después de haber extraído las características
df = df.drop(columns=['captured_at_dt'], errors='ignore')

print("Dataset después de la ingeniería de características de tiempo y expansión de 'features':")
display(df.head())

"""### 🗑️ Verificación de Valores Faltantes"""

# Contar valores faltantes por columna
missing_values = df.isnull().sum()
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({'Missing Count': missing_values, 'Missing Percentage (%)': missing_percentage})
missing_df = missing_df[missing_df['Missing Count'] > 0].sort_values(by='Missing Percentage (%)', ascending=False)

if not missing_df.empty:
    print("Columnas con valores faltantes:")
    display(missing_df)
else:
    print("No hay valores faltantes en el dataset.")

"""### 📊 Distribución de Variables Numéricas"""

# Para las columnas numéricas con valores faltantes, imputaremos con la media para las visualizaciones.
# Esto es solo para fines de visualización en el EDA, no modifica el DataFrame para el modelado.

df_eda = df.copy()
for col in df_eda.select_dtypes(include=['float64', 'int64']).columns:
    if df_eda[col].isnull().any():
        df_eda[col] = df_eda[col].fillna(df_eda[col].mean())

# Seleccionar columnas numéricas
numerical_cols = df_eda.select_dtypes(include=['int64', 'float64']).columns
print(f"Columnas numéricas identificadas: {list(numerical_cols)}")
print(f"Número de columnas numéricas: {len(numerical_cols)}")

if len(numerical_cols) > 0:
    # Calcular el número de filas necesario para la cuadrícula de subplots (3 columnas por fila)
    n_rows = (len(numerical_cols) + 2) // 3
    fig, axes = plt.subplots(n_rows, 3, figsize=(18, 5 * n_rows))
    axes = axes.flatten() # Aplanar el array de axes para fácil iteración

    for i, col in enumerate(numerical_cols):
        sns.histplot(df_eda[col], kde=True, ax=axes[i]) # Usamos df_eda que ya tiene los NaN imputados
        axes[i].set_title(f'Distribución de {col}')
        axes[i].set_xlabel(col)
        axes[i].set_ylabel('Frecuencia')

    # Desactivar los subplots vacíos si los hay
    for j in range(i + 1, len(axes)):
        if j < len(axes):
            fig.delaxes(axes[j])

    plt.tight_layout()
    plt.show()
else:
    print("No se encontraron columnas numéricas para graficar.")

"""### Categorías de Variables Categóricas"""

# Seleccionar columnas categóricas
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
print(f"Columnas categóricas identificadas: {list(categorical_cols)}")
print(f"Número de columnas categóricas: {len(categorical_cols)}")

if len(categorical_cols) > 0:
    # Calcular el número de filas necesario para la cuadrícula de subplots (2 columnas por fila)
    n_rows_cat = (len(categorical_cols) + 1) // 2
    fig_cat, axes_cat = plt.subplots(n_rows_cat, 2, figsize=(15, 6 * n_rows_cat))
    axes_cat = axes_cat.flatten() # Aplanar el array de axes para fácil iteración

    for i, col in enumerate(categorical_cols):
        top_categories = df[col].value_counts().nlargest(10)
        sns.barplot(x=top_categories.index, y=top_categories.values, palette='viridis', ax=axes_cat[i])
        axes_cat[i].set_title(f'Distribución de {col} (Top 10)')
        axes_cat[i].set_xlabel(col)
        axes_cat[i].set_ylabel('Frecuencia')
        axes_cat[i].tick_params(axis='x', rotation=45)

    # Desactivar los subplots vacíos si los hay
    for j in range(i + 1, len(axes_cat)):
        if j < len(axes_cat):
            fig_cat.delaxes(axes_cat[j])

    plt.tight_layout()
    plt.show()
else:
    print("No se encontraron columnas categóricas para graficar.")

from sklearn.preprocessing import LabelEncoder

# Codificar la columna 'label' (variable objetivo) y 'phase'
le_label = LabelEncoder()
df['label_encoded'] = le_label.fit_transform(df['label'])
print(f"Clases de 'label' codificadas: {list(le_label.classes_)}")

le_phase = LabelEncoder()
df['phase_encoded'] = le_phase.fit_transform(df['phase'])
print(f"Clases de 'phase' codificadas: {list(le_phase.classes_)}")

# Eliminamos las columnas originales 'label' y 'phase' si ya no se necesitan en este formato
df = df.drop(columns=['label', 'phase'])

print("Dataset final listo para modelado (primeras 5 filas):")
display(df.head())

"""### 🛠️ Imputación de Valores Faltantes"""

# Imputar los valores faltantes en las columnas numéricas del DataFrame 'df'
# Usaremos la mediana para ser robustos a posibles valores atípicos.
for col in df.select_dtypes(include=['float64', 'int64']).columns:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].median())

print("Verificación final de valores faltantes después de la imputación:")
display(df.isnull().sum()[df.isnull().sum() > 0])

print("Dataset listo después de la imputación (primeras 5 filas):")
display(df.head())

"""### 💾 Guardar el Dataset Procesado en un Archivo CSV"""

# Guardar el DataFrame procesado a un archivo CSV
# Usamos index=False para no incluir el índice de pandas como una columna en el CSV
output_file_path = 'df_processed.csv'
df.to_csv(output_file_path, index=False)

print(f"Dataset procesado guardado exitosamente en: {output_file_path}")

"""Ahora, el archivo `df_processed.csv` contiene el dataset con todas las características ingenierizadas, valores faltantes imputados, y variables categóricas codificadas, listo para ser cargado y utilizado en un nuevo cuaderno para las tareas de modelado."""