# -*- coding: utf-8 -*-
"""ModeloSupervisado2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rSBTt7XsHDq4NBvIB6zvSQPrf4xO2Bzb
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# 1. CARGA Y LIMPIEZA DEL DATASET
df = pd.read_csv('/content/df_processed.csv')

# Definimos explícitamente las 6 columnas que SÍ queremos mantener
columnas_deseadas = [
    'left_knee_angle', 'right_knee_angle',
    'left_hip_angle', 'right_hip_angle',
    'trunk_inclination', 'knee_angle_mean', 'label_encoded'
]

# Filtramos el dataframe para quedarnos solo con lo necesario
df = df[columnas_deseadas]

# 2. PREPARACIÓN DE DATOS
X = df.drop('label_encoded', axis=1)
y = df['label_encoded']

# Dividimos con stratify
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

# 3. ESCALADO
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. ENTRENAMIENTO DEL MODELO
rf_clf = RandomForestClassifier(n_estimators=250, criterion='entropy', random_state=42)
rf_clf.fit(X_train_scaled, y_train)

# Evaluación rápida
rf_preds = rf_clf.predict(X_test_scaled)
print(f"Columnas finales usadas ({len(X.columns)}): {list(X.columns)}")
print(f"Accuracy final del modelo RF: {accuracy_score(y_test, rf_preds):.4f}")

# 5. FUNCIÓN DE PREDICCIÓN
def predecir_calidad_rf(datos_nuevos):
    """
    datos_nuevos: Lista con 6 valores [l_knee, r_knee, l_hip, r_hip, trunk, knee_mean]
    """
    nombres_columnas = X.columns
    datos_df = pd.DataFrame(np.array(datos_nuevos).reshape(1, -1), columns=nombres_columnas)
    datos_escalados = scaler.transform(datos_df)
    prediccion = rf_clf.predict(datos_escalados)
    return "Correcto" if prediccion[0] == 0 else "Incorrecto"

# 6. PRUEBA CON 6 DATOS
ejemplo_input = [147.19, 89.98, 168.32, 127.29, 3.51, 118.58]
resultado = predecir_calidad_rf(ejemplo_input)
print(f"\nResultado de la predicción: {resultado}")