# -*- coding: utf-8 -*-
"""ModeloSupervisado2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rSBTt7XsHDq4NBvIB6zvSQPrf4xO2Bzb
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# 1. CARGA Y LIMPIEZA DEL DATASET (Paso crítico para el 88%)
df = pd.read_csv('/content/df_processed.csv')

# Eliminamos las columnas de ruido que degradan el modelo
df = df.drop(columns=['id', 'rep_count', 'hour_of_day', 'day_of_week', 'month', 'phase_encoded'])

# 2. PREPARACIÓN DE DATOS
X = df.drop('label_encoded', axis=1)
y = df['label_encoded']

# Dividimos con stratify para mantener el balance de clases
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

# 3. ESCALADO (Obligatorio para que la función de predicción funcione igual que el entrenamiento)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. ENTRENAMIENTO DEL MODELO GANADOR (Random Forest)
# Usamos los parámetros que dieron el mejor resultado
rf_clf = RandomForestClassifier(n_estimators=250, criterion='entropy', random_state=42)
rf_clf.fit(X_train_scaled, y_train)

# Evaluación rápida para confirmar estado
rf_preds = rf_clf.predict(X_test_scaled)
print(f"Accuracy final del modelo RF: {accuracy_score(y_test, rf_preds):.4f}")

# ==============================================================================
# 5. FUNCIÓN DE IMPLEMENTACIÓN (PREDICCIÓN)
# ==============================================================================
def predecir_calidad_rf(datos_nuevos):
    """
    Realiza una predicción de calidad de sentadilla utilizando Random Forest.
    datos_nuevos: Lista con los 9 ángulos/distancias obtenidos de Mediapipe.
    """
    # El modelo espera exactamente estas 9 columnas en este orden:
    # [left_knee, right_knee, left_hip, right_hip, left_ankle, right_ankle, trunk, dist_knees, dist_ankles]
    nombres_columnas = X.columns

    # Convertir la lista a DataFrame para que el Scaler reconozca los nombres de las features
    datos_df = pd.DataFrame(np.array(datos_nuevos).reshape(1, -1), columns=nombres_columnas)

    # 1. Escalar usando el mismo scaler del entrenamiento
    datos_escalados = scaler.transform(datos_df)

    # 2. Realizar la predicción
    prediccion = rf_clf.predict(datos_escalados)

    # 0 = Correcto, 1 = Incorrecto
    return "Correcto" if prediccion[0] == 0 else "Incorrecto"

# ==============================================================================
# 6. EJEMPLO DE IMPLEMENTACIÓN REAL
# ==============================================================================
# Estos 9 valores son los que extraes en tiempo real con tu script de Mediapipe
ejemplo_input = [175.0, 174.0, 178.0, 177.0, 89.0, 90.0, 5.0, 0.35, 0.40]

resultado = predecir_calidad_rf(ejemplo_input)
print(f"\nResultado de la predicción: {resultado}")